### ISSUE TITLE
Goto anything quick panel list backend bits [$30]

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#122]
I've not been thinking about how to implement this at all so it's pretty open. This issue number deals *just* with the backend management of the quick panel list, not actually filling the list in with content which are dealt with in other issues marked with the [goto](https://github.com/limetext/lime/issues?direction=desc&labels=goto) label.

* Each list item is required to have a title, but can also have optional metadata.
* It should be possible to execute a fuzzy search in the list to get matches
* There should be a event callback when the the current item is changed (think arrow up/arrow down)
* There should be an event callback when an item is selected (think enter)
* There should be an event callback when the panel is dismissed (think esc)

Rather than someone jumping straight in and implementing it with a pull request, I think it'd be wise to brainstorm a bit to draft up the interfaces involved with the different modes possible for the [goto anything](https://github.com/limetext/lime/issues?direction=desc&labels=goto) functionality.

**Comment by derekparker** [comment]
@quarnster regarding this issue - have you taken a look at https://github.com/derekparker/trie? Each list item could be stored in the trie data structure, and searched with efficient prefix or fuzzy searching. The data structure also allows for arbitrary metadata to be stored alongside each list item, and the title could be the key.

The structure has efficient storage and search properties, and population of the structure is efficient as well. Usage of this package would adhere to the above requirements, and would easily satisfy a callback API - imagine performing a fuzzy search with `trie.FuzzySearch` as the user is typing, and then once the `selected` callback happens when a user determins their selection, that entire string of their selection could be passed to `trie.Find` if the metadata was needed.

**Comment by quarnster** [comment]
@derekparker Haven't thought about this issue in quite a while but looks like your package would indeed be useful. Thanks for the pointer

**Comment by derekparker** [comment]
@quarnster cool, I can try and work on a patch for this during the week. I've been absent from this project for a while busy with some other things but I'd like to get back into helping out, I really like this project.

**Comment by quarnster** [comment]
@derekparker Glad to hear it, all help is highly appreciated. BTW haven't had a chance to look at [delve](https://github.com/derekparker/delve) yet but looking forward to it when it works on OSX and I'm in need of some Go debugging in the future :)

**Comment by quarnster** [comment]
@derekparker Semi-related: delve would be an ideal use case in figuring out where the standard Sublime Text plugin API lacks with regards to creating custom UI elements and how we can improve upon that. But we should probably have that discussion in a separate issue number.

**Comment by derekparker** [comment]
@quarnster cool I'd love to discuss that more. Delve should be available on OS X soon!

**Comment by zoli** [comment]
Moved to https://github.com/limetext/backend/issues/105.
