### ISSUE TITLE
[ARM] build on ArchLinuxARM

### ISSUE THREAD

**Issue by heradon** [limetext/lime#232]
```
[ 75%] Generating ../backend/sublime/region_generated.go
# lime/3rdparty/libs/rubex
/usr/bin/ld: /home/odroid/code/go/src/lime/build/dist/lib/libonig.a(regerror.o): relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/home/odroid/code/go/src/lime/build/dist/lib/libonig.a: error adding symbols: Bad value
collect2: Fehler: ld gab 1 als Ende-Status zurück
CMakeFiles/fix.dir/build.make:79: recipe for target '../backend/sublime/region_generated.go' failed
make[2]: *** [../backend/sublime/region_generated.go] Error 2
CMakeFiles/Makefile2:133: recipe for target 'CMakeFiles/fix.dir/all' failed
make[1]: *** [CMakeFiles/fix.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2 
```

**Comment by jimson-jimson** [comment]
My attempts at getting the html-frontend working on an ARM Chromebook (Acer Chrombook 13) running Xubuntu 14.04 armhf have been so far unsuccesful.

I'm not quite sure if its because I'm on ARM or if I'm just ignorant to go, as my ignorance to go is a matter of fact not speculation. I can't get any of the other frontends working either, and it's rather dissapointing, as my other adventures in compiling software for ARM have gone considerably well so far.

`user@chrubuntu:~/golang/src/github.com/limetext/lime/frontend/html$ go run main.go`
`SIGILL: illegal instruction`
`PC=0xb6af93d2`

Sad Times

**Comment by zoli** [comment]
@jimson-jimson what are the result of tests?

**Comment by heradon** [comment]
not working on ARM

**Comment by zoli** [comment]
This is https://github.com/limetext/support related issue.
