### ISSUE TITLE
How to compile/install?

### ISSUE THREAD

**Issue by IonicaBizau** [limetext/lime#270]
This project is great. How can I compile and install it on my Ubuntu 14.04?

**Comment by stayorgo** [comment]
Hrm, it seems to me that one should be able to download an Exe or a Elf, or a tar gz and run the program in one easy step, rather than fiddling around for 30 or more minutes chasing wild geese. The whole point of Go (and delphi) is that you download a single Exe and deploy in one step.  These browser based web app type new kids on the block don't seem to understand the whole point of web apps - which was to make the program easy to use - just load up your browser, and boom there your program runs... It seems to me that all these web kits, build instructions, download this, download that, defeats the whole purpose of using a computer. Computers are supposed to make our lives easier, not more difficult.  I will try to work on an installer for all this fragmented nonsense required just to start using a Go IDE - but if anyone has one already or someone is already working on one, let me know.  And yes I know it is not a typical Exe that uses the Win API so it's a bit different, but still - all these hoops you have to jump through just to install Lime Text Editor is pathetic. It's called getting work done - I don't need to know a million things about the build process in order just to start using Go IDE, do I? Oh yes I do.  Consider someone goes to buy a Mac or iPad and instead of providing you with the computer, you have to build it yourself from the solder to the flux, to the capacitors. What is this, gentoo?  The amount of global warming caused by people building stuff they don't need to build...... 3 billion CPU cycles lost to the heat death of the universe..

**Comment by linktohack** [comment]
Except that you are going to be disappointed because the exe/elf etc can not do anything good at the moment except showing some source code and... quit. It's mentioned on the Main Page that the frontend is not ready that.

**Comment by gwenzek** [comment]
I installed Lime on my ubuntu 14.04.
As it requires python 3.5 I had to install it through a non-official ppa: [http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu](http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu)
Is it okay to link this ppa in the wiki install page, while no official ubuntu channel has python3.5 ?

**Comment by erbridge** [comment]
@gwenzek: yes, please. I thought it was already, but feel free to add it if it isn't.

**Comment by gwenzek** [comment]
@erbridge  done :-)
