### ISSUE TITLE
QML Line Numbers

### ISSUE THREAD

**Issue by bawigga** [limetext/lime#516]
The QML frontend needs to support line numbers.

Sublime Text has a setting called `line_numbers` that is a boolean. See [the Sublime Text Unofficial Documentation](http://docs.sublimetext.info/en/latest/reference/settings.html?highlight=line_numbers)

See #164 for more context and discussions on the termbox frontend implementation.

**Comment by marcieivie** [comment]
Ok 12 23 54 dddlcc.p

**Comment by quarnster** [comment]
Since the QML frontend treats each line as a separate item, it should be trivial to add in line numbers. The line number will just be the "index" (or index+1) of the QML data model.

**Comment by bawigga** [comment]
Is there any backend infrastructure that supports a Gutter? I'm thinking of ST plugins like [GitGutter](https://github.com/jisaacks/GitGutter) or SublimeLinter that add artifcats next to the line numbers.

**Comment by quarnster** [comment]
Gutter icons are specified via [view.AddRegions](http://godoc.org/github.com/limetext/lime/backend#View.AddRegions). This is how the syntax highlighting, spelling error-squiggly lines and other text metadata is specified too. It's the job of [View.Transform](http://godoc.org/github.com/limetext/lime/backend#View.Transform) and [render.Transform](http://godoc.org/github.com/limetext/lime/backend/render#Transform) to take all that data into account, usually with the help of [Recipie.Transcribe](http://godoc.org/github.com/limetext/lime/backend/render#Recipe.Transcribe) too.

Though it looks like [render.Flavour](http://godoc.org/github.com/limetext/lime/backend/render#Flavour) needs to be expanded with an icon field, and [render.ViewRegionFlags](http://godoc.org/github.com/limetext/lime/backend/render#ViewRegionFlags) should probably have a DRAW_ICON const added.

To make it easier for frontends, `render.Transform` should probably split all DRAW_ICON Flavours so that they are just DRAW_ICON Flavours in a zero sized region containing the start point of the region it's associated with.

**Comment by erbridge** [comment]
Migrated to limetext/lime-qml#1.
