### ISSUE TITLE
osx: sublime test failure (test_toxt)

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#531]
The issue is with "reload_test.py" where it looks (to me) like the "test_toxt" command doesn't run and the view's contents remain empty instead thus failing the assert.

**Comment by jivid** [comment]
The problem seems to be that "test_toxt" never gets registered as a valid command. When CommandHandler.RunTextCommand is called as a side-effect of line 8 in reload_test.py, "test_toxt" is never found. I'm going to take a stab at fixing the error (unless someone's already looking at it).

This is my first day looking at lime's source code, so I apologize in advance for any rookie questions that might follow :smile:
