### ISSUE TITLE
Please update build instructions

### ISSUE THREAD

**Issue by askalski** [limetext/lime#562]
Hi,

I wanted to contribute to project, but being new in Go I was unable to even build it. I closely followed instructions from wiki about ubuntu 14.04, diverging only in fact that ubuntu provides python 3.5 via repository, so with no ppa. Also, I used golang 1.6, default available.

Could anyone please update build instructions, either for ubuntu 15.10 or 16.04 (probably better idea)?

Kindest Regards

**Comment by Chiniara** [comment]
A way to build in windows would be good too! I want to contribute and it seems there isnt even a way to build it on windows.

**Comment by ricochet1k** [comment]
I would recommend sticking with Go 1.5, 1.6 is not going to work yet.

The easiest way to build on Windows is to use Msys2, but download and extract Go 1.5.3 manually, don't use the one from the repository. I have built and run Lime-QML on Windows this way and it works fine, with a few minor Qt hiccups.

**Comment by rgson** [comment]
You can use golang1.6 if you set the environment variable `GODEBUG` to `cgocheck=0` (i.e. `export GODEBUG=cgocheck=0`). More details can be found in limetext/lime-qml#16.

**Comment by jlvivero** [comment]
another thing is that there's no backend/lib/ anymore, since it got moved to the root folder, which caused a lot of confusion for me.

Even after I found out when i try to get the term frontend working, it's looking for the filed on backend/lib/ so i get an error (gonna try creating the backend/lib/ directory again and adding the original files there and see if it works)

**Comment by rgson** [comment]
I have just created a fully automated build script for Ubuntu 16.04: https://github.com/limetext/lime/wiki/Building-on-Ubuntu-16.04.

Currently it only covers the backend and the QML frontend due to the issues with Termbox and HTML that was just mentioned by @jlvivero. I'll look into how they can be built correctly when I have more time, and add them to the build script if I get them working.

The script has been tested and verified on a fresh install of Ubuntu 16.04 (ubuntu-16.04-desktop-amd64).

**Comment by jlvivero** [comment]
There's a pull request on the Termbox repo currently that I think addresses that issue. So it's just a matter of time before that frontend is functioning as well

**Comment by erbridge** [comment]
I just updated the main building instructions. It's too much work for us to maintain the platform specific pages, but if you come across issues on them, please feel free to fix them (it's why we have a wiki).

The termbox and html frontends are currently broken, but I'm looking at getting them working again.

**Comment by erbridge** [comment]
And thanks for the Ubuntu 16.04 instructions @rgson!
