### ISSUE TITLE
My country can not get some packages and build failed.

### ISSUE THREAD

**Issue by xsjqqq123** [limetext/lime#567]
I really want to try this soft. I try to built it last night . but some of go packages can not get because of the Great Firewall of China。is there any prebuild "setup.exe" or " *.deb "?  thanks very much.

**Comment by Viomi** [comment]
Not something that can be fixed by the devs of limetext, but this just means you'll have to use a pre-built copy of limetext.

If you can say what OS you're running and what kind of package you want (.deb or .exe), I'm sure someone could provide you with binaries.

Just remember that binaries from third parties are risky and could include malware.

**Comment by zoli** [comment]
It's not ready for daily usage.
